# Numpy Documentation Study by Jales Bussinguer

### This notebook is a review of Numpy's documentation. The main goal here is to learn the classes, objects, methods, functions and all the application capabilities in a spatial data analysis using satellite imagery.

All content in this study was taken from the official website of the documentation, and are available [here](https://docs.scipy.org/doc/).

First of all, Numpy is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

* NumPy arrays have a fixed size at creation. Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

## The Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy, dimensions are called *axes*.

Numpy's array class is called **ndarray**. The more important attributes of an ndarray object are:

* ndarray.ndim( ) -> <font color=blue> The number of axes (dimensions) of the array.</font>

* ndarray.shape( ) -> <font color=blue> The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with *n* rows and *m* columns, $ shape $ will be (n,m). The lenght of the $ shape $ tuple is therefore the number of axes, $ ndim $.

* ndarray.size( ) -> <font color=blue> The total number of elements of the array. This is equal to the product of the elements of shape.

* ndarray.dtype( ) -> ,<font color=blue> Describes the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. **numpy.int32**, **numpy.int16**, and **numpy.float64** are some examples.

* ndarray.itemsize( ) -> <font color=blue> The size in bytes of each element of the array. For example, an array of elements of type **float64** has itemsize 8 (=64/8), while one of type **complex32** has itemsize 4 (=32/8). It is equivalent to **ndarray.dtype.itemsize**.

* ndarray.data( ) -> <font color=blue> The buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

#### An Example

In [6]:
import numpy as np

In [25]:
a = np.arange(15).reshape(3,5)
# This variable creates an array of 3 axes with lenght 5, in all 3
# using a sequence of numbers from 0 to 14.

# [Important]: In Python, the count initiates in 0.
# So, the first number in a sequence will always be the number 0.

a # Returns the output of the variable

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a.shape # Return the dimensions of the array

(3, 5)

In [33]:
a.ndim # The number of dimensions of the array

2

In [34]:
a.dtype.name # The type of the elements in the data

# The 'string' part is the type (integer, float, string, complex, ...)
# The 'numeric' part is the number of bits (8, 16, 32, 64, ...)

'int32'

In [36]:
a.itemsize # The size in bytes of each element of the array.

# Basically, this object divide the number of bits by 8.

4

In [37]:
a.size # The total number of elements of the array

15

In [39]:
type(a) # The type of data. In this case, a NumPy n-dimensional array.

numpy.ndarray

### Array Creation

There are several ways to create arrays.

**1. Creating an array from a regular Python list or tuple using the $ array $ function. The tyoe of the resulting array is deduced from the type of the elements in the sequences.**

In [59]:
import numpy as np

a = np.array([2,3,4])
print('a =',a)
print ('The type of the elements is', a.dtype)

b = np.array([1.2,3.5,5.1])
print('b =',b)
print('The type of the elements is', b.dtype)

a = [2 3 4]
The type of the elements is int32
b = [1.2 3.5 5.1]
The type of the elements is float64


**2. Transforming sequences of sequences into n-dimensional arrays.**

In [56]:
import numpy as np

b = np.array([(1.5,2,3), (4,5,6)])
print('b =',b)

# This is an array with 2 axes.

b = [[1.5 2.  3. ]
 [4.  5.  6. ]]


**- The type of the array can also be explicitly specified at creation time:**

In [55]:
c = np.array([[1,2],[3,4]], dtype=complex)
print('c =', c)

c = [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


**3. Creating an array of zeros and then populating the placeholders.**

If the elements of an array are originally unknown, but the size is known, we can create an array of zeros with the known size. Later, we can populate the array placeholders.

In [71]:
np.zeros((3,4)) # Creates an array of n axes and lenght m.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

We can also create an array of ones. The data type can also be specified

In [75]:
np.ones((2,3,4), dtype=np.int64)
# Creates 2 arrays of 3 axes and lenght 4 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

An empty array can also be created. However, the output may vary because the array is uninitialized)

In [82]:
np.empty((3,3)) # Creates an empty array of 3 axes and lenght 3.

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.03549480e-321],
       [1.02360527e-306, 9.34590097e-307, 1.78020033e-306]])

**4. Creating a sequence of numbers using the function arange( )**

To create sequences of numbers, NumPy provides a function analogous to $ range $ (Python built-in) that return arrays instead of lists.

In [85]:
np.arange(10,30,5)
# Creates a sequence of numbers from 10 to 30 with a step of 5
# The last term is not included in the array (in this case, 30)

array([10, 15, 20, 25])

In [87]:
np.arange(0,2,0.3)
# The function accpets float-type arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

**<font color=green> [Important]**: <font color=black> When $ arange( ) $ is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function $ linspace $ that receives as an argument the number of elements that we want, instead of the step:

In [89]:
from numpy import pi

np.linspace(0,2,9) 
# An array that contains 9 numbers from 0 to 2.
# By using this function, the last term is included
# (in this case, 2)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### Printing Arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

* the last axis is printed from left to right,

* the second-to-last is printed from top to bottom,

* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [94]:
a = np.arange(6) # 1d array
print('a =',a)

a = [0 1 2 3 4 5]


In [100]:
b = np.arange(12).reshape(4,3) # 2d array
print('b =',b)

b = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [101]:
c = np.arange(24).reshape(2,3,4) # 3d array
print('C =',c) 

C = [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


The details of the shape change (reshape method) are [here] (#Shape Manipulation).

### Basic Operations

Arithmetic operators on arrays apply *elementwise*. A new array is created and filled with the result.

In [104]:
a = np.array([20,30,40,50]) # An 1d array

b = np.arange(4) # An array of a sequential numbers from 0 to 3
print('b =',b)

b = [0 1 2 3]


In [107]:
# Addition

c = a+b
print('c =',c)

c = [20 31 42 53]


In [108]:
# Subtraction

c = a-b
print('c =', c)

c = [20 29 38 47]


In [122]:
# Multiplication (elementwise)

c = a*b
print('c =',c)

c = [  0  30  80 150]


Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [126]:
# Matrix product

a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

c = a @ b
print('c =',c)

d = a.dot(b)
print('d =',d)

c = [[5 4]
 [3 4]]
d = [[5 4]
 [3 4]]


In [112]:
# Division

c = a/b
print('c =', c)

#In this case, we have and division by zero. 
# See the warning message printed below.

c = [        inf 30.         20.         16.66666667]


C:\Users\jales\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [114]:
# Power

c = b**2
print('c =', c)

c = [0 1 4 9]


In [121]:
# Boolean

a<35

array([ True,  True, False, False])